Account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'Account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', LoginView.as_view(template_name='Account/signin.html'), name='signin'),
    path('signout/', LogoutView.as_view(next_page='Account:signin'), name='signout'),

]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path("addtocart/<int:product_id>/", views.add_to_cart, name='addtocart'),
    path("removefromcart/<int:cart_item_id>/", views.remove_from_cart, name='removefromcart'),
    path("cart_detail", views.cart_detail, name='cart_detail'),

    path('increment_units/<int:cart_item_id>/', views.increment_units, name='increment_units'),
    path('decrement_units/<int:cart_item_id>/', views.decrement_units, name='decrement_units'),

    path("mpesa_pay/<int:id>/", views.mpesa_pay, name='mpesa_pay'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('index/', views.index, name='index')
]

market/urls.py
from django.urls import include, path
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    path('Account/', include('Account.urls')),

    # products
    path("", include("product.urls")),

    # dashboard urls
    path("dashboard/", include("dashboard.urls")),

    # cart urls
    path("cart/", include("cart.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views


app_name = "product"

urlpatterns = [
    path("", views.home, name="home"),
    path('create_product/', views.create_product, name='create_product'),
    path('product_details/<int:id>/', views.product_details, name='product_details'),
    path('update_product/<int:id>', views.update_product, name='update_product'),
    path('delete_product/<int:id>', views.delete_product, name='delete_product'),

    path("product_search/", views.product_search, name="product_search"),
]

Account/models.py
from django.db import models

Account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):

    # phone = forms.IntegerField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

Account/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import RegistrationForm


def signup(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active=True
            user.save()
            messages.success(request, 'Account Created Successfully', extra_tags="success")
            return redirect('Account:signin')
        else:
            messages.error(request, 'Unsuccessful Registration', extra_tags="error")

    form = RegistrationForm()
    return render(request, 'Account/signup.html', {'form':form})

Account/templates/navbar.html
{% load static %}


<style>
  /* Style for navbar */
  .navbar {
      background-color: #9cd11a;
      padding: 02px;
  }

  .navbar-brand img {
      border-radius: 50%;
      width: 100px;
      height: 100px;
  }

  .navbar-nav .nav-link {
      color: #343333;
      font-weight: bold;
      margin-right: 10px;
  }

  .navbar-nav .active {
      color: #555;
  }

  .navbar-toggler {
      border: none;
      outline: none;
  }

  .navbar-toggler-icon {
      background-color: #9cd11a;
  }

  .navbar-nav.ml-auto .nav-item {
      margin-left: 10px;
  }

  .navbar-nav.ml-auto .nav-link {
      /*color: #fff;
      background-color: #333;*/
      border: solid 1px #333;
      padding: 8px 10px;
      border-radius: 50px;
      display: flex;
  }

  .navbar-nav.ml-auto .nav-link:hover {
      background-color: #9cd11a;
  }
</style>



<nav class="navbar navbar-expand-lg shadow-sm" style="background-color: #fafafa;">
  <div class="container-fluid text-center">
      <a class="navbar-brand" href="{% url 'product:home' %}">
        <img src="{% static 'Account/assets/logo.png' %}" style="border-radius: 10%; width: 150px; height: 80px" alt="logo">
      </a>
      <a class="nav-link " href="/product_search/"> <i class="fa-solid fa-magnifying-glass"> &nbsp; </i>Search</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link active border-0" aria-current="page" href="{% url 'product:home' %}">Home</a>
              </li>
          </ul>

          <div class="container color-white">
            <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'product:create_product' %}"><strong>SELL</strong></a>
                  </li>

                  {% if user.is_authenticated %}
                    <!-- Visible to authenticated users -->
                    <li class="nav-item">
                      <a class="nav-link border-0" href="{% url 'cart:cart_detail'  %}">Cart</a>
                    </li>

                    <li class="nav-item">
                      <a class="nav-link border-0" href="{% url 'dashboard:index'  %}">Dashboard</a>
                    </li>

                    <li class="nav-item">
                      <a class="nav-link border-0" href="{% url 'Account:signout' %}">Sign Out</a>
                    </li>

                  {% else %}
                    <!-- Visible to non-authenticated users -->
                    <li class="nav-item">
                        <a class="nav-link border-0" href="{% url 'Account:signin' %}">Sign In</a>
                      </li>
                        <li class="nav-item">
                      </li>
                          <a class="nav-link border-0" href="{% url 'Account:signup' %}">Sign Up</a>
                    </li>

                  {% endif %}
            </ul>
          </div>

      </div>
  </div>
</nav>