cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path("addtocart/<int:product_id>/", views.add_to_cart, name='addtocart'),
    path("removefromcart/<int:cart_item_id>/", views.remove_from_cart, name='removefromcart'),
    path("cart_detail", views.cart_detail, name='cart_detail'),

    path('increment_units/<int:cart_item_id>/', views.increment_units, name='increment_units'),
    path('decrement_units/<int:cart_item_id>/', views.decrement_units, name='decrement_units'),

    path("mpesa_pay/<int:id>/", views.mpesa_pay, name='mpesa_pay'),
]

market/urls.py
from django.urls import include, path
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    path('Account/', include('Account.urls')),

    # products
    path("", include("product.urls")),

    # dashboard urls
    path("dashboard/", include("dashboard.urls")),

    # cart urls
    path("cart/", include("cart.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views


app_name = "product"

urlpatterns = [
    path("", views.home, name="home"),
    path('create_product/', views.create_product, name='create_product'),
    path('product_details/<int:id>/', views.product_details, name='product_details'),
    path('update_product/<int:id>', views.update_product, name='update_product'),
    path('delete_product/<int:id>', views.delete_product, name='delete_product'),

    path("product_search/", views.product_search, name="product_search"),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from product.models import Product

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    units =models.IntegerField(default=1)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return f"{self.units} x {self.product.name}"
    
    def save(self, *args, **kwargs):
        if self.product.unit_price is not None:
            self.total_price = self.product.unit_price * self.units
        super(Cart, self).save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('cart:cart_detail')

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from product.models import Product

from django.http import HttpResponse
from django_daraja.mpesa.core import MpesaClient

from .models import Cart

@login_required
def add_to_cart(request, product_id):
    # get product instance with given id
    product = get_object_or_404(Product, id=product_id)

    try:
        cart_item = Cart.objects.get(user=request.user, product=product)
        cart_item.units += 1
        cart_item.save()
        messages.success(request, "Item added to Cart")
    except Cart.DoesNotExist:
        Cart.objects.create(user=request.user, product=product)
        messages.success(request, "Item added to Cart")

    return redirect('product:home')


@login_required
def remove_from_cart(request, cart_item_id):
    cart_item = get_object_or_404(Cart, id=cart_item_id)

    if cart_item.user == request.user:
        cart_item.delete()
        messages.success(request, 'Item removed from Cart')

    return redirect('cart:cart_detail')

@login_required
def cart_detail(request):
    cart_items = Cart.objects.filter(user=request.user)
    total_price = sum(item.units * item.product.unit_price for item in cart_items)

    context = {
        'cart_items': cart_items,
        'total_price': total_price
    }

    return render(request, "cart/cart_detail.html", context)

@login_required
def increment_units(request, cart_item_id):
    cart_item = get_object_or_404(Cart, id=cart_item_id)

    if cart_item.user == request.user:
        cart_item.units += 1
        cart_item.save()

    return redirect('cart:cart_detail')

@login_required
def decrement_units(request, cart_item_id):
    cart_item = get_object_or_404(Cart, id=cart_item_id)

    if cart_item.user == request.user:
        if cart_item.units > 1:
            cart_item.units -= 1
            cart_item.save()

    return redirect('cart:cart_detail')


# mpesa view
@login_required
def mpesa_pay(request, id):
    if request.method == 'POST':
        phone_number = request.POST.get('phone_number')
        cl = MpesaClient()

        try:
            cart_items = Cart.objects.filter(user_id=id)
            total_price = 0

            for cart_item in cart_items:
                total_price += cart_item.total_price

            account_reference = cart_items.first().id
            description = f"{len(cart_items)} items in the cart. Total price: {total_price}."
            callback_url = 'https://api.darajambili.com/express-payment'

            cl.stk_push(phone_number, int(total_price), account_reference, description, callback_url)

            return redirect("cart:cart_detail")
        except Cart.DoesNotExist:
            return HttpResponse("Cart not found")

cart/templates/cart/cart_detail.html
{% extends 'Account/base.html' %}

{% block content %}
{% load static %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            {% for item in cart_items %}
            <div class="card mb-3">
                <div class="card-body text-capitalize">
                    <h2 class="card-title text-capitalize">{{ item.product.name }}</h2>
                    <p class="card-text">Each at: {{ item.product.price }} </p>
                    <p class="card-text">Each unit has: {{ item.product.quantity }} {{ item.product.name }}</p>
                    <p class="card-text">Units: {{ item.units }}</p>
                    <p class="card-text">Price (per unit): {{ item.product.unit_price }} Rupees</p>

                    <div class="row" style="max-width: 120px"  >
                        <div class="col">
                            <form method="post" action="{% url 'cart:increment_units' item.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary" >+</button>
                            </form>
                        </div>

                        <div class="col">
                            <form method="post" action="{% url 'cart:decrement_units' item.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-warning">-</button>
                            </form>
                        </div>
                    </div>

                    <a href="{% url 'cart:removefromcart' item.id %}" class="btn mt-3" style="background-color:#ff7c1a; color:white">Remove from Cart</a>
                </div>
            </div>
            {% endfor %}

            <h4>Total Price:{{ total_price }} Rupees</h4>
        </div>

        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <form method="post" action="{% url 'cart:mpesa_pay' request.user.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <p style="font-family: Arial, sans-serif; font-size: 16px; font-weight: bold;">Scan and pay:</p>
                            <img src="{% static 'Account/assets/qr.jpg' %}" style="border-radius: 1%; width: 250px; height: 250px" alt="Scan and pay">
                          <!--  <label for="phone_number">Enter Phone Number:</label>
                            <input type="text" name="phone_number" id="phone_number" class="form-control" required>
                        </div>
                        <button type="submit" class="btn border-0 mt-2" style="background-color:#9cd11a; color:white">Pay with M-Pesa</button>
                    </form>-->
                </div>


                    <div class="card-body">
                        <a href="{% url 'product:home' %}" class="btn btn-info mt-3 text-light" style="background-color:#ff7c1a; color:white">Continue Shopping</a>
                    </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}