cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path("addtocart/<int:product_id>/", views.add_to_cart, name='addtocart'),
    path("removefromcart/<int:cart_item_id>/", views.remove_from_cart, name='removefromcart'),
    path("cart_detail", views.cart_detail, name='cart_detail'),

    path('increment_units/<int:cart_item_id>/', views.increment_units, name='increment_units'),
    path('decrement_units/<int:cart_item_id>/', views.decrement_units, name='decrement_units'),

    path("mpesa_pay/<int:id>/", views.mpesa_pay, name='mpesa_pay'),
]

market/urls.py
from django.urls import include, path
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    path('Account/', include('Account.urls')),

    # products
    path("", include("product.urls")),

    # dashboard urls
    path("dashboard/", include("dashboard.urls")),

    # cart urls
    path("cart/", include("cart.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views


app_name = "product"

urlpatterns = [
    path("", views.home, name="home"),
    path('create_product/', views.create_product, name='create_product'),
    path('product_details/<int:id>/', views.product_details, name='product_details'),
    path('update_product/<int:id>', views.update_product, name='update_product'),
    path('delete_product/<int:id>', views.delete_product, name='delete_product'),

    path("product_search/", views.product_search, name="product_search"),
]

product/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):

    CATEGORIES = (
        ("Vegetables", "Vegetables"),
        ("Fruits", "Fruits"),
        ("Meat, Poultry & Dairy", "Meat, Poultry & Dairy"),
        ("Farm Feeds", "Farm Feeds")
    )

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    category = models.CharField(max_length=25, default="Vegetables", choices=CATEGORIES)
    quantity = models.IntegerField(default=5)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to="products")
    price = models.IntegerField()
    location = models.CharField(max_length=50)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def save(self, *args, **kwargs):
        # Calculate and set the unit_price when saving the object.
        self.unit_price = self.price * self.quantity
        super(Product, self).save(*args, **kwargs)


    def __str__(self):
        return f"{self.name}-({self.quantity}) by {self.owner}"

product/forms.py
from django import forms
from .models import Product

class CreateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category','quantity', 'description','image', 'price', 'location']

class UpdateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category','quantity', 'description','image', 'price', 'location']


class ProductSearchForm(forms.Form):
    name = forms.CharField(required=False, label='Search by name')
    location = forms.CharField(required=False, label='Search by location')
    category_choices = list(Product.CATEGORIES)  # Convert to a list
    category = forms.ChoiceField(
        required=False,
        label='Category',
        choices=[('', 'Select a category')] + category_choices
    )

product/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from PIL import Image
from django.core.files.uploadedfile import InMemoryUploadedFile
from io import BytesIO
from django.db.models import Q

from django.core.paginator import Paginator

from .forms import CreateProductForm, UpdateProductForm, ProductSearchForm
from .models import Product


def home(request):
    products_list = Product.objects.all().order_by("id")[::-1]
    paginator = Paginator(products_list, 12)

    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    return render(request, "product/home.html", {"products": products})


@login_required
def create_product(request):
    if request.method == 'POST':
        form = CreateProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.owner = request.user

            # Check and process the image if it exists
            image = form.cleaned_data.get('image')
            if image:
                img = Image.open(image)
                max_image_size = (500, 500)
                img.thumbnail(max_image_size)
                img_data = BytesIO()
                img.save(img_data, format='JPEG', quality=80)  # You can change format and quality as needed
                img_data.seek(0)

                # Assign the processed image back to the form field
                form.cleaned_data['image'] = InMemoryUploadedFile(
                    img_data,
                    None,
                    image.name,
                    'image/jpeg',
                    img_data.tell(),
                    None
                )

            product.save()
            messages.success(request, f"{form.cleaned_data['name']} posted!", extra_tags="success")
            return redirect('dashboard:index')
        else:
            print(form.errors)
            messages.error(request, 'Unsuccessful!', extra_tags="error")

    form = CreateProductForm()

    return render(request, 'product/create_product.html', {"form": form})



def product_details(request, id):
    product = Product.objects.get(id=id)
    # print(product)
    items = Product.objects.filter(category=product.category)
    return render(request, "product/product_details.html", {'product': product, 'items': items,})


@login_required
def update_product(request, id):

    product = get_object_or_404(Product, id=id, owner=request.user)

    if request.method == "POST":
        form = UpdateProductForm(request.POST, request.FILES, instance=product)

        if form.is_valid():
            form.save()

            messages.success(request, "product updated successfully!", extra_tags="success")
            return redirect("product:product_details", id=product.id)
    else:
        form = UpdateProductForm(instance=product)

    context = {
        "form": form
    }

    return render(request, "product/update_product.html", context)

@login_required
def delete_product(request, id):
    product = get_object_or_404(Product, id=id, owner=request.user)
    product.delete()
    messages.warning(request, "product deleted!", extra_tags="warning")

    return redirect('product:home')


def product_search(request):
    form = ProductSearchForm(request.GET)
    products = Product.objects.all()

    if form.is_valid():
        name = form.cleaned_data.get('name')
        location = form.cleaned_data.get('location')
        category = form.cleaned_data.get('category')

        if name:
            products = products.filter(Q(name__icontains=name))

        if location:
            products = products.filter(Q(location__icontains=location))

        if category and category != 'Select a category':
            products = products.filter(Q(category=category))

    context = {
        'form': form,
        'products': products
    }
    return render(request, 'product/product_search.html', context)

product/templates/product/create_product.html
{% extends 'Account/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <h2 class="card-title text-center text-success">Create new product</h2>
                    <hr>
                    <form action="" method="POST" class="form-control" enctype="multipart/form-data" >
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-success mt-2 btn-block" type="submit">Upload</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

product/templates/product/home.html
{% extends 'Account/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-3">
    <div class="container mt-3 mb-4 text-center">
        <img>
        <h2 class="text mb-4" style="font-family: 'montserrat'; font-weight: 700; color:#9cd11a;">"Harvesting the Future: Shop Direct from Kenyan Fields!"</h2>
        <p class="text mb-4" style="font-family: 'montserrat';">We foster a sustainable ecosystem where farmers can thrive, <br>while making shopping for fresh and quality produce a breeze while supporting the growth of local agriculture.</p>
        <p style="font-family: 'Chi'; color:#04371a; font-size: 24px;">Happy Shopping!</p>
    </div>

    <div class="row">
        {% for product in products %}
        <div class="col-md-3">
            <div class="card mt-3 border-0 shadow-sm">
                <a class="text-decoration-none" href="{% url 'product:product_details' product.id %}">
                    <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}" style="height: 200px; object-fit: cover; width: 100%; border-top-left-radius:10px; border-top-right-radius:10px;">
                    <div class="card-body">
                        <h2 class="card-title text-black text-capitalize fs-6 mb-1">{{ product.name }}</h2>
                        <p class="card-text text-dark" style="font-weight: 100;">Desc: {{ product.description|truncatewords:2 }}</p>
                        <p class="card-text fw-3" style="color:#ff7c1a;">Price: {{ product.unit_price }} Rupees</p>
                    </div>

                    <div class="cart m-3" style="width: 50px;">
                        </a>
                        <a href="{% url 'cart:addtocart' product.id %}" class="text-decoration-none">
                            <i class="fa-solid fa-shopping-cart" style="color: #9cd11a;"></i>
                        </a>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
</div>

<div class="d-flex justify-content-center m-4">
    <div class="pagination">
        <span class="step-links">
            {% if products.has_previous %}
                <a class="btn btn-info" href="?page=1">First</a>
                <a class="btn btn-dark" href="?page={{ products.previous_page_number }}">Prev</a>
            {% endif %}

            <span class="current-page">
                Page <strong class="text-dark">{{ products.number }}</strong>  of {{ products.paginator.num_pages }}.
            </span>

            {% if products.has_next %}
                 <a class="btn btn-info" style="background-color: #9cd11a;" href="?page={{ products.next_page_number }}">Next</a>
                  <a class="btn btn-dark" style="background-color: #04371a;" href="?page={{ products.paginator.num_pages }}">Last</a>
            {% endif %}
        </span>
    </div>
</div>
<footer class="footer mt-3 py-3" style="background: #04371a;">
    <div class="container">
      <div class="row">
        <div class="col-md-6 text-white">
            <h5 class="text-decoration-underline text-white" style="font-size: 16px;">Contact Us:</h5>
            <p style="font-size: 12px;">Binil ,Arjun ,Aswin ,Amalraj</p>
            <p style="font-size: 12px;">Email: info@farmersmarket.com</p>
            <p style="font-size: 12px;">Phone: +91**********</p>
          </div>

        <div class="col-md-6 text-white">
          <h5 class="text-white" style="font-size: 16px;">Follow Us</h5>
          <a class="btn text-white" href="https://www.facebook.com/binil.john.716970?mibextid=ZbWKwL"><i class="fab fa-facebook">&nbsp;</i> Facebook</a><br>
          <a class="btn text-white" href="https://x.com/_binil_john_?t=XThL_zWG29ZMP9gxBFx8RQ&s=09"><i class="fab fa-x">&nbsp;</i> Twitter </a><br>
          <a class="btn text-white" href="https://www.instagram.com/ashwin_asok?igsh=MWZoZ3M5bG0yMnVlOA=="><i class="fab fa-instagram">&nbsp;</i> Instagram</a>
        </div>
      </div>
      <div class="row text-center mt-2 text-dark" style="background-color: #9cd11a; border-radius: 20px;">
        <p class="mt-1 mb-1"> <strong> Farmers Market &nbsp; <i class="fa-solid fa-copyright"></i></strong> &nbsp; {% now "Y" %} </p>
      </div>
    </div>
  </footer>
{% endblock content %}

product/templates/product/product_details.html
{% extends 'Account/base.html' %}

{% block content %}



<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <div class="text-center">
            <h2 class="text-capitalize" >{{ product.name }}</h2>
                <img class="img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}" style="height: 400px; object-fit: cover; width: 100%;">
            </div>
        </div>
        <div class="col-md-6 mt-5">
            <h5 class="text-decoration-underline mb-4" style="color: #04371a;">Details:</h5>
            <p> <strong class="fw-bold">Each at:</strong> {{ product.price }} Rupees</p>
            <p> <strong class="fw-bold">Minimum quantity:</strong> {{ product.quantity }}</p>
            <p> <strong class="fw-bold">Minimum order:</strong> {{ product.unit_price }}</p>
            <p class="text-capitalize"> <strong class="fw-bold">Description:</strong> {{ product.description }}</p>
           <p class="text-capitalize"> <strong class="fw-bold">Location:</strong > {{ product.location }}</p>
            {% if request.user.username != product.owner.username %}
                <a href="{% url 'cart:addtocart' product.id %}" class="btn btn-primary mt-3 border-0" style="background-color: #9cd11a;">Add to Cart</a>
            {% endif %}
            {% if request.user.username == product.owner.username %}
                <a href="{% url 'product:update_product' product.id %}" class="btn btn-info">Update</a>
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Delete
                  </button>

            {% endif %}
        </div>


        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete this product</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="{% url 'product:delete_product' product.id %}" class="btn btn-danger" >Delete</a>
                </div>
            </div>
            </div>
        </div>


    </div>
    <h3 class="mt-5 text-center display-8 fw-bold mb-3" style="color: #04371a;">Similar Products</h3>
    <div class="row">
        {% for item in items %}
            <div class="col-md-2 mb-4">
                <div class="card">
                    <a  class="text-decoration-none" href="{% url 'product:product_details' item.id %}">
                        <img class="card-img-top" src="{{ item.image.url }}" alt="{{ item.name }}" style="height: 200px; object-fit: cover; width: 100%;">
                        <div class="card-body">
                            <h2 class="card-title fs-6 text-capitalize text-dark">{{ item.name }}</h2>
                            <p class="card-text" style="color: #ff7c1a;">Price:{{ item.price }} Rupees</p>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

product/templates/product/product_search.html
{% extends 'Account/base.html' %}

{% load crispy_forms_tags %}


{% block content %}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-12">
            <form method="get" action="{% url 'product:product_search' %}">
                <div class="form-row align-items-center m-2">
                    <div class="col-md-3">
                        {{ form.name.label_tag }}
                        {{ form.name }}
                    </div>
                 <!--   <div class="col-md-3 mt-2">
                        {{ form.location.label_tag }}
                        {{ form.location }}
                    </div>-->
                    <div class="col-md-3 mt-2">
                        {{ form.category.label_tag }}
                        {{ form.category }}
                    </div>
                    <div class="col-md-3 mt-3">
                        <button type="submit" class="btn btn-warning">Filter &nbsp; <i class="fa-solid fa-filter"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>




<div class="container mt-3">
    <div class="row">
        {% for product in products %}
        <div class="col-md-3 p-2">
            <div class="card h-80 mt-3">
                <a class="text-decoration-none" href="{% url 'product:product_details' product.id %}">
                    <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}" style="height: 200px; object-fit: cover; width: 100%;">
                </a>
                <div class="card-body text-capitalize">
                    <h2 class="card-title text-black text-capitalize fs-4">{{ product.name }}</h2>
                    <p class="card-text text-danger fw-2">Price: {{ product.unit_price }}</p>
                    <p><strong class="fw-bold">Each at:</strong> {{ product.price }}</p>
                    <p><strong class="fw-bold">Minimum quantity:</strong> {{ product.quantity }}</p>
                    <p><strong class="fw-bold">Minimum order:</strong> {{ product.unit_price }}</p>
                    <p><strong class="fw-bold">Description:</strong> {{ product.description }}</p>
                   <!-- <p class="text-capitalize"> <strong class="fw-bold">Location:</strong> {{ product.location }}</p>-->
                </div>
                <a href="{% url 'cart:addtocart' product.id %}" class="text-decoration-none color-warning">
                    <i class="fa-solid fa-shopping-cart"></i>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}
    

product/templates/product/update_product.html
{% extends 'Account/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <h2 class="card-title text-center text-success">Update</h2>
                    <hr>
                    <form action="" method="POST" class="form-control">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-success mt-2 btn-block" type="submit">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}