cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path("addtocart/<int:product_id>/", views.add_to_cart, name='addtocart'),
    path("removefromcart/<int:cart_item_id>/", views.remove_from_cart, name='removefromcart'),
    path("cart_detail", views.cart_detail, name='cart_detail'),

    path('increment_units/<int:cart_item_id>/', views.increment_units, name='increment_units'),
    path('decrement_units/<int:cart_item_id>/', views.decrement_units, name='decrement_units'),

    path("mpesa_pay/<int:id>/", views.mpesa_pay, name='mpesa_pay'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('index/', views.index, name='index')
]

market/urls.py
from django.urls import include, path
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    path('Account/', include('Account.urls')),

    # products
    path("", include("product.urls")),

    # dashboard urls
    path("dashboard/", include("dashboard.urls")),

    # cart urls
    path("cart/", include("cart.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views


app_name = "product"

urlpatterns = [
    path("", views.home, name="home"),
    path('create_product/', views.create_product, name='create_product'),
    path('product_details/<int:id>/', views.product_details, name='product_details'),
    path('update_product/<int:id>', views.update_product, name='update_product'),
    path('delete_product/<int:id>', views.delete_product, name='delete_product'),

    path("product_search/", views.product_search, name="product_search"),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render

from product.models import Product

def index(request):
    products = Product.objects.filter(owner=request.user)

    return render(request, 'dashboard/index.html', {'products': products})

dashboard/templates/dashboard/index.html
{% extends 'Account/base.html' %}

{% block content %}
<div class="container">
    <h1 class="text-capitalize mt-3 mb-2" style="color:#04371a; font-size: 24px;">{{ request.user.username }}</h1>
    <h3 class="text-capitalize mb-3 text-center" style="color:#ff7c1a; font-size: 24px;">your items</h3>

    <div class="row">
        {% for product in products %}
            <div class="col-md-3">
                <a class="text-decoration-none" href="{% url 'product:product_details' product.id %}">
                <div class="card mb-4 text-capitalize">
                    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" style="height: 200px; object-fit: cover; width: 100%;">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Price: {{ product.price }}</li>
                        <li class="list-group-item">Quantity: {{ product.quantity }}</li>
                    </ul>
                </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock %}